version: '2.1'

volumes:
   geoserver-data:
   geo-db-data:
        
networks:
  geo-net:
    driver: bridge

services:
   geo-init:
      build:
         context: .
         dockerfile: ./geo-init.Dockerfile
      networks:
         - geo-net
      depends_on:
        - geoserver

   db:
      build:
         context: .
         dockerfile: ./postgis.Dockerfile
      networks:
         - geo-net
      volumes:
         - geo-db-data:/var/lib/postgresql
      ports:
        - "25434:5432"

   geoserver:
      build:
         context: .
         dockerfile: ./geoserver.Dockerfile
      networks:
         - geo-net
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
      ports:
        - "8080:8080"
      depends_on:
        - db


