version: '2.1'

volumes:
   geoserver-data:
   geo-db-data:

networks:
  geo-net:
    driver: bridge

services:
   web:
      container_name: api_rest
      build:
         context: .
         dockerfile: ./web.Dockerfile
      networks:
         - geo-net
      ports:
        - "5000:5000"
      depends_on:
        - postgresql

   geo-init:
      build:
         context: .
         dockerfile: ./geo-init.Dockerfile
      networks:
         - geo-net
      depends_on:
         - geoserver

   postgresql:
      container_name: postgresql
      build:
         context: .
         dockerfile: ./postgis.Dockerfile
      networks:
         - geo-net
      volumes:
         - geo-db-data:/var/lib/postgresql
      ports:
        - "25434:5432"

   geoserver:
      container_name: geoserver
      build:
         context: .
         dockerfile: ./geoserver.Dockerfile
      networks:
         - geo-net
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
      ports:
        - "8081:8080"
      depends_on:
        - postgresql
